# Generated by Django 5.2.6 on 2025-09-14 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mutualist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='Prenoms')),
                ('last_name', models.CharField(max_length=25, verbose_name='Nom')),
                ('phone_number', models.CharField(max_length=10, verbose_name='Numero')),
            ],
            options={
                'verbose_name': 'Mutualiste',
                'verbose_name_plural': 'Mutualistes',
            },
        ),
        migrations.CreateModel(
            name='Sms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('mutualists', models.ManyToManyField(to='sendingsms.mutualist')),
            ],
            options={
                'verbose_name': 'SMS',
                'verbose_name_plural': 'SMS',
            },
        ),
    ]
